
package com.nsbdev.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DataSaverWsImplService", targetNamespace = "http://ws.nsbdev.com/", wsdlLocation = "http://localhost:8080/saver?wsdl")
public class DataSaverWsImplService
    extends Service
{

    private final static URL DATASAVERWSIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException DATASAVERWSIMPLSERVICE_EXCEPTION;
    private final static QName DATASAVERWSIMPLSERVICE_QNAME = new QName("http://ws.nsbdev.com/", "DataSaverWsImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/saver?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DATASAVERWSIMPLSERVICE_WSDL_LOCATION = url;
        DATASAVERWSIMPLSERVICE_EXCEPTION = e;
    }

    public DataSaverWsImplService() {
        super(__getWsdlLocation(), DATASAVERWSIMPLSERVICE_QNAME);
    }

    public DataSaverWsImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DATASAVERWSIMPLSERVICE_QNAME, features);
    }

    public DataSaverWsImplService(URL wsdlLocation) {
        super(wsdlLocation, DATASAVERWSIMPLSERVICE_QNAME);
    }

    public DataSaverWsImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DATASAVERWSIMPLSERVICE_QNAME, features);
    }

    public DataSaverWsImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DataSaverWsImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DataSaverWs
     */
    @WebEndpoint(name = "DataSaverWsImplPort")
    public DataSaverWs getDataSaverWsImplPort() {
        return super.getPort(new QName("http://ws.nsbdev.com/", "DataSaverWsImplPort"), DataSaverWs.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DataSaverWs
     */
    @WebEndpoint(name = "DataSaverWsImplPort")
    public DataSaverWs getDataSaverWsImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.nsbdev.com/", "DataSaverWsImplPort"), DataSaverWs.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DATASAVERWSIMPLSERVICE_EXCEPTION!= null) {
            throw DATASAVERWSIMPLSERVICE_EXCEPTION;
        }
        return DATASAVERWSIMPLSERVICE_WSDL_LOCATION;
    }

}
