
package com.nsbdev.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.nsbdev.beans.TransferMessage;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DataSaverWs", targetNamespace = "http://ws.nsbdev.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DataSaverWs {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "saveToDB", targetNamespace = "http://ws.nsbdev.com/", className = "com.nsbdev.ws.SaveToDB")
    @ResponseWrapper(localName = "saveToDBResponse", targetNamespace = "http://ws.nsbdev.com/", className = "com.nsbdev.ws.SaveToDBResponse")
    @Action(input = "http://ws.nsbdev.com/DataSaverWs/saveToDBRequest", output = "http://ws.nsbdev.com/DataSaverWs/saveToDBResponse")
    public String saveToDB(
        @WebParam(name = "arg0", targetNamespace = "")
        TransferMessage arg0);

}
